### ISSUE TITLE
Support []string and []*string as sensitive fields

### ISSUE THREAD

**Issue by turkenh** [crossplane/terrajet#100]
### What problem are you facing?

Tring to generate a CRD with sensitive field type []*string fails with:

```
panic: cannot generate crd: cannot build types for User: cannot build the types: got type "[]*string" for field "Passwords", only types "string" and "*string" supported as sensitive
```

```
config.Store.SetForResource("aws_elasticache_user", config.Resource{
		ExternalName: config.ExternalName{
			DisableNameInitializer: true,
		},
		Sensitive: config.Sensitive{
			CustomFieldPaths: []string{
				"passwords", // interestingly this field is not marked as sensitive in tf schema
			},
		},
		UseAsync: true,
	})
```

### How could Terrajet help solve your problem?

Support []string and []*string as sensitive fields

**Comment by turkenh** [comment]
In GCP, I got the following for `google_storage_bucket_object`:

```console
panic: cannot generate crd for resource google_storage_bucket_object: cannot build types for BucketObject: cannot build the Types: got type "[]github.com/crossplane-contrib/provider-tf-gcp/apis/storage/v1alpha1.CustomerEncryptionParameters" for field "CustomerEncryption", only types "string" and "*string" supported as sensitive
```

However, I believe this is different than the above cases since here as struct type is marked as sensitive. I think it would be enough/safe just to ignore it as long as the parameters of the struct are marked as sensitive, which we would need to handle indeed.

**Comment by muvaf** [comment]
@turkenh are you planning to support `map[string]*string` as well?
