### ISSUE TITLE
Update configuring resource guide per latest changes

### ISSUE THREAD

**Issue by turkenh** [crossplane/terrajet#153]
### What happened?

There are couple of changes in Terrajet configuration interface that happened after the `Configuring a resource` guide is introduced [first time](https://github.com/crossplane-contrib/provider-jet-aws/pull/123).

We need to update the guide accordingly.

There are a couple of review comments in https://github.com/crossplane-contrib/terrajet/pull/130 which we would need to tackle first: 

- https://github.com/crossplane-contrib/terrajet/pull/130#discussion_r749507600
- https://github.com/crossplane-contrib/terrajet/pull/130#discussion_r749508451
- https://github.com/crossplane-contrib/terrajet/pull/130#discussion_r752947141
- https://github.com/crossplane-contrib/terrajet/pull/130#discussion_r752947828
- https://github.com/crossplane-contrib/terrajet/pull/130#discussion_r749516661

### How can we reproduce it?

Reflect latest changes to the guide.

**Comment by muvaf** [comment]
Just dropping note, we should add instructions about this ability https://github.com/crossplane-contrib/provider-jet-azure/issues/110
