### ISSUE TITLE
Confusion of `github_repository` in getting started doc

### ISSUE THREAD

**Issue by zzxwill** [crossplane/terrajet#226]
### What happened?

I got confused about `github_repository` in https://github.com/crossplane/terrajet/blob/main/docs/generating-a-provider.md?plain=1#L155. After that, I realized it refer to a Terraform resource of the provider.

Maybe we should make it more clear on `github_repository`.

**Comment by turkenh** [comment]
Thanks for the feedback @zzxwill 

I hope 1db626737a33b38383077925152acb7dc22cac89 should fix this.

**Comment by zzxwill** [comment]
@turkenh It should. Thanks. 

BTW, can you help take a look at this PR? https://github.com/crossplane/provider-alibaba/pull/72
