### ISSUE TITLE
Object 'apiVersion' is missing in 'kind: CustomResourceDefinition

### ISSUE THREAD

**Issue by mikebollandajw** [crossplane/terrajet#249]
### What happened?
Trying to install provider after building and pushing to dockerhub

```
kubectl crossplane install provider ajwportalteam/provider-jet-azuread-amd64:v0.1.0
```

But providerrevision object reports

![image](https://user-images.githubusercontent.com/38316056/156325993-d9fea681-d3a7-4757-b208-8076805d6209.png)

Did I miss a step in the guide? make run is fine

### How can we reproduce it?
Use same image / source at https://github.com/ajwgroup/provider-jet-azuread

**Comment by muvaf** [comment]
It seems like the first line is deleted for some reason by the crd cleaning target. But I see you're on terrajet v0.4.0 now, so you don't need that target at all, removal looks like [this](https://github.com/crossplane-contrib/provider-jet-template/pull/17). Removing it and running `make reviewable` should get you to a working state.

**Comment by muvaf** [comment]
@mikebollandajw feel free to reopen if the suggestion doesn't work.

**Comment by mikebollandajw** [comment]
am i supposed to delete something before attemping the command again? i am still getting the same error

```kubectl crossplane install provider ajwportalteam/provider-jet-azuread-amd64:v0.1.0```

``` kubectl describe providerrevision ajwportalteam-provider-jet-azuread-amd64-b71584c8e9bb```

 Normal   BindClusterRole    110s (x4 over 111s)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole to provider ServiceAccount(s)
  Normal   ApplyClusterRoles  110s (x4 over 111s)  rbac/providerrevision.pkg.crossplane.io      Applied RBAC ClusterRoles
  Warning  ParsePackage       53s (x7 over 110s)   packages/providerrevision.pkg.crossplane.io  cannot parse package contents: Object 'apiVersion' is missing in 'kind: CustomResourceDefinition

**Comment by muvaf** [comment]
You need to fix the code itself like this and regenerate the package https://github.com/crossplane-contrib/provider-jet-template/pull/17

**Comment by mikebollandajw** [comment]
but i did all that right in my commit

**Comment by muvaf** [comment]
Could you rebuild your package with the change? I downloaded `ajwportalteam/provider-jet-azuread-amd64:v0.1.0` and its CRDs (in `/package.yaml`) still doesn't have the `apiVersion`

**Comment by mikebollandajw** [comment]
oh the image of course, sorry!

**Comment by mikebollandajw** [comment]
relates to https://github.com/crossplane-contrib/provider-jet-template/issues/19

**Comment by mikebollandajw** [comment]
FATA[0003] Couldn't mount blobs for cross-repository push: Blob mount failed to url https://registry-1.docker.io/v2/ajwportalteam/provider-jet-azuread/blobs/uploads/?from=ajwportalteam%2Fprovider-jet-azuread-amd64&mount=sha256%3Aec0d4dfaf649ce85448b101a8c31cdef54e16de4a20f3edb2222accecbc0136f: HTTP status 401
15:18:17 [FAIL]
build/makelib/image.mk:218: recipe for target 'img.release.manifest.publish.provider-jet-azuread' failed
make[1]: *** [img.release.manifest.publish.provider-jet-azuread] Error 1
build/makelib/common.mk:395: recipe for target 'publish' failed

**Comment by mikebollandajw** [comment]
i also had to remove the arm64 due to it failing to build

mikebolland@A-00090-LT10797:/mnt/c/dev/git/provider-jet-azuread$ make publish
14:39:25 [ .. ] docker build crossplane/provider-jet-azuread-amd64:v0.0.0-17.g1faa222
14:39:26 [ OK ] docker build crossplane/provider-jet-azuread-amd64:v0.0.0-17.g1faa222
14:39:26 [ .. ] docker build crossplane/provider-jet-azuread-arm64:v0.0.0-17.g1faa222
Error response from daemon: No such image: build-160414ad/provider-jet-azuread-arm64:latest
14:39:26 [FAIL]
build/makelib/image.mk:215: recipe for target 'img.release.build.crossplane.provider-jet-azuread.arm64' failed

**Comment by mikebollandajw** [comment]
> FATA[0003] Couldn't mount blobs for cross-repository push: Blob mount failed to url https://registry-1.docker.io/v2/ajwportalteam/provider-jet-azuread/blobs/uploads/?from=ajwportalteam%2Fprovider-jet-azuread-amd64&mount=sha256%3Aec0d4dfaf649ce85448b101a8c31cdef54e16de4a20f3edb2222accecbc0136f: HTTP status 401 15:18:17 [FAIL] build/makelib/image.mk:218: recipe for target 'img.release.manifest.publish.provider-jet-azuread' failed make[1]: *** [img.release.manifest.publish.provider-jet-azuread] Error 1 build/makelib/common.mk:395: recipe for target 'publish' failed

for anyone reading this who have a similar issue try removing .docker in your home drive i had a repo defined there that seemed to have been picked up by this causing an error

**Comment by mikebollandajw** [comment]
so i have managed to deploy this my final issue that remains is that the crossplane management pod is trying to read from the crossplane docker repo

![image](https://user-images.githubusercontent.com/38316056/158966574-a5a1f4b2-b58e-4325-b5b4-b61e7cc33f28.png)

despite the fact in my makefile the dockerrepo is set to ajwgroup

i have editted the pod for now however i worry something is not reading from the correct makefile value

**Comment by mikebollandajw** [comment]
perhaps this is cluster/images/provider-jet-azuread/Makefile

**Comment by muvaf** [comment]
@mikebollandajw [This](https://github.com/ajwgroup/provider-jet-azuread/blob/aeaf75e/Makefile#L53) is the line that gives the docker registry to use and it's defined with `?=`, meaning it can be overridden via env var defined in your shell. So, I'd suggest checking what might be overriding it by running `echo $DOCKER_REGISTRY` before running `make` commands.
