### ISSUE TITLE
cann't find executable file in $PATH. cannot init workspace

### ISSUE THREAD

**Issue by bretagne-peiqi** [crossplane/terrajet#265]
### What happened?
generate alicloud-jet-provider using terrajet and followed the guide.

build provider binary and runs with:
./provider --terraform-provider-source=aliyun/alicloud  --terraform-provider-version=1.155.0  --terraform-version=terraform-1.1.5 --debug

![image](https://user-images.githubusercontent.com/5621794/158945564-23f9cee3-de01-4b5b-a445-1ad22926b375.png)

### How can we reproduce it?
deploy crossplane version 1.6.2 in k8s cluster; run provider binary as metioned above.  apply crds and securitygroups template.

**Comment by bretagne-peiqi** [comment]
the terraform-1.1.5 binary is in my $PATH， I can execute from a terminal

**Comment by bretagne-peiqi** [comment]
fixed

**Comment by dhano6** [comment]
@bretagne-peiqi 

Hi,

I am having exactly the same error, how did you resolve it please?

**Comment by bretagne-peiqi** [comment]
check the network. by default, it will download it from terraform.io
