### ISSUE TITLE
How to deploy into existing infrastructure?

### ISSUE THREAD

**Issue by waldner** [crossplane/terrajet#285]
As you might imagine, crossplane might sometimes be used to deploy only some resources into an already established (ie created outside of crossplane) cloud infrastructure. In general, I think it's fair to assume that there will be cases where not ALL of the infrastructure is managed with crossplane, so that resources being created with crossplane have to integrate with existing objects.

Terraform handles this very straightforwardly with data sources, which allow users to discover and supply the right object ids (regardless of whether they were created with terraform or not) to resources that need those references, _without the user having to know the actual id_.

Does crossplane/terrajet have similar mechanisms? As far as I can tell, in the above scenario one has to discover (via some OOB mechanism) the object ids of the existing resources and use them directly in the crossplane managed resource YAML, which can be quite inconvenient.

How hard would it be for the project to implement this feature? I feel that this would add even more value (and use cases) to this already powerful tool.

**Comment by ytsarev** [comment]
Hi @waldner , vary valid points, it is actively discussed in a core crossplane, see https://github.com/crossplane/crossplane/issues/1722

**Comment by waldner** [comment]
Thanks, I will subscribe to that thread and close this one.
