### ISSUE TITLE
Blogpost about Terrajet

### ISSUE THREAD

**Issue by luebken** [crossplane/terrajet#54]
### What problem are you facing?
Terrajet is a new project that needs visibility. We should create a blog post that announces this new project alongside with the new 3 providers

### How could Terrajet help solve your problem?
Create a blogpost that describes the idea and the status.

**Comment by Kahavens** [comment]
@muvaf  Can you add this to the marketing repo so that I have access to add it to projects?

**Comment by Kahavens** [comment]
Do we have a link to this content yet or is it still in the works? @muvaf

**Comment by muvaf** [comment]
@Kahavens it's still in the works. I'll share the draft link in the private issue once it's ready for review.

**Comment by muvaf** [comment]
Published https://blog.crossplane.io/deep-dive-terrajet-part-i/
